### ISSUE TITLE
org.terasology.jnlua.LuaRuntimeException: error loading module 'pb' from file:undefined symbol: lua_gettop

### ISSUE THREAD

**Issue by xudong1031** [MovingBlocks/JNLua#13]
org.terasology.jnlua.LuaRuntimeException: error loading module 'pb' from file '/usr/local/lib/lua/5.3/pb.so':
        /usr/local/lib/lua/5.3/pb.so: undefined symbol: lua_gettop
        at org.terasology.jnlua.LuaState53.lua_pcall(Native Method)
        at org.terasology.jnlua.LuaState.call(LuaState.java:733)
        at Main.main(Main.java:16)

**Comment by xudong1031** [comment]
I want to load 'pb. so' but reported an error
