### ISSUE TITLE
dynamic libraries not enabled; check your Lua installation

### ISSUE THREAD

**Issue by zxj12530** [MovingBlocks/JNLua#4]
i test on macosx but got this error

```
Exception in thread "main" org.terasology.jnlua.LuaRuntimeException: error loading module 'cjson' from file '/usr/local/lib/lua/5.3/cjson.so':
  dynamic libraries not enabled; check your Lua installation
  at org.terasology.jnlua.LuaState53.lua_pcall(Native Method)
  at org.terasology.jnlua.LuaState.call(LuaState.java:733)
  at org.terasology.jnlua.test.LuaScriptTest.callLua(LuaScriptTest.java:23)
  at org.terasology.jnlua.test.LuaScriptTest.main(LuaScriptTest.java:14)

```

**Comment by asiekierka** [comment]
The default-compiled natives should not allow loading external libraries from the Lua side, as that would be a security concern in the context we're using JNLua in. You may have to add additional compile flags.

**Comment by zxj12530** [comment]
Can you give some advice? We commonly use macosx and linux

**Comment by zxj12530** [comment]
We use lua5.1 is normal, why 5.3 will have security concern?

**Comment by zxj12530** [comment]
Thank you, I have modified LUA_TYPE to macosx and linux, but still report the error.

**Comment by asiekierka** [comment]
Try passing -DLUA_USE_DLOPEN directly, then. Maybe that will do.

**Comment by zxj12530** [comment]
I followed the instructions you said, I did the following:

(1) Modify Makefile.mac
         CFLAGS?=-O2 -DLUA_USE_MACOSX -DLUA_USE_DLOPEN

(2) modify build-natives-eris_mac.sh
        LUA_TYPE="posix" is changed to LUA_TYPE="macosx"

(3) Generate libjnlua-5.3-mac-amd64.dylib and put it under /Library/Java/Extensions
(4)./gradlew build generates JNLua-0.1.0-SNAPSHOT.jar
(5) My project uses the Lua5.3 version, and the cjson library compiled with 5.3

When I execute the call, I still get an error.

```
Exception in thread "main" org.terasology.jnlua.LuaRuntimeException: error loading module 'cjson' from file '/usr/local/lib/lua/5.3/cjson.so':
Dynamic libraries not enabled; check your Lua installation
```

**Comment by asiekierka** [comment]
You forgot to modify the CFLAGS in the shell script itself. Makefile.mac controls the building logic of the Java glue and does not control Lua itself.

Modfiy MY_LUA_CFLAGS in the shell script.

**Comment by zxj12530** [comment]
Hello, there is still a problem, I see "This branch of Eris currently comes with Lua 5.3.0"

We tested with lua5.3.5

Will this version of the difference affect?

**Comment by asiekierka** [comment]
>Will this version of the difference affect?

The branch actually comes with Lua 5.3.5. A bit of text has not been updated, I suppose.

**Comment by zxj12530** [comment]
ok，thank you！
